LogLevel: "INFO"
Encipher: "vPQC5LWCN2CW2opz"

Emby:
  url: "http://127.0.0.1"
  port: 8096
  apiKey: "apikey"

# 多后端配置列表
Backends:
  # 顺序不重要，程序会自动优先匹配最长路径
  - name: "Media-A"
    url: "https://stream-gd.example.com/stream"
    path: "/Media-A"

  - name: "115_c"
    url: "https://stream-gd.example.com/stream"
    path: "/media/115_c"

  - name: "GoogleDrive"
    url: "https://stream-gd.example.com/stream"
    path: "/mnt/gd"

PlayURLMaxAliveTime: 21600
Server:
  port: 60001

SpecialMedias:
  - key: "MediaMissing"
    name: "Default media for missing cases"
    mediaPath: "specialMedia/mediaMissing"
    itemId: "mediaMissing-id"
    mediaSourceID: "mediaMissing-source-id"
